<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0;net11.0</TargetFrameworks>
    <OutputPath>..\Bin\Cli</OutputPath>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>Pek.Office.Cli</AssemblyName>
    <RootNamespace>Pek.Office.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DH.NCore" Version="4.25.2026.911-beta0202" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pek.Office\Pek.Office.csproj" />
  </ItemGroup>

</Project>
